### ISSUE TITLE
Determine the canonical test matrix to support

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/modulesync_config#113]
Continued from #111.

@jyaworski I am not aware of anything canonical. However, two sources are about as close as you can get:

https://github.com/puppetlabs/modulesync_configs/blob/master/config_defaults.yml#L4-L12
https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/.travis.yml#L6-L20

The latter is very much long in the tooth (some outstanding PRs to narrow it down), so I think it's wise to go with the former as the most official-ish test matrix.

Regardless, it's up to us to decide what we care about. I think we've all agreed that ruby 1.8.7 and Puppet 3 are out; that we don't want to get involved in point releases of Puppet versions; and that we want STRICT_VARIABLES on at all times and P3+FUTURE_PARSER in the matrix.

My [personal opinion on ruby versions](https://github.com/rnelson0/puppet-modulesync_config/blob/master/config_defaults.yml) is to test 1.9.3, 2.1.0, and 2.3.0, because those are the boundaries where things tend to have broken in the past, whereas 2.0 and 2.2 did not cause breakage. However, 2.3.0 can still cause breakage so it's in allow_failures, and only tested against P4. This gives a matrix with 7 entries, one of which can fail, so it's larger than I'd like but not overly so, and appears to have benefits by crossing the dangerous version boundaries. We may want to explore something like that, plus one version of the jruby version if we can determine what puppetserver uses and test only that branch.

**Comment by jyaworski** [comment]
Puppetserver's jruby mode is 1.9.3 on 1.x and 2.x both. That should definitely be included, possibly with 3.x and FUTURE_PARSER.

**Comment by jyaworski** [comment]
Confirming....

```shell
[root@puppet1 ~]# rpm -q puppetserver
puppetserver-1.1.3-1.el7.noarch
[root@puppet1 ~]# puppetserver ruby -e 'puts RUBY_VERSION; puts JRUBY_VERSION'
1.9.3
1.7.20.1
```
```shell
[root@puppet2 ~]# rpm -q puppetserver
puppetserver-2.3.1-1.el7.noarch
[root@puppet2 ~]# puppetserver ruby -e 'puts RUBY_VERSION; puts JRUBY_VERSION'
1.9.3
1.7.20.1
```

**Comment by jyaworski** [comment]
I propose the following:

```yaml
  - rvm: 1.9
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test FUTURE_PARSER=yes
  - rvm: jruby-19mode
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test JRUBY_OPTS="-J -Xmx1024M --debug" FUTURE_PARSER=yes
  - rvm: jruby-19mode
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test JRUBY_OPTS="-J -Xmx1024M --debug"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.3
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
  allow_failures:
  - rvm: 2.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
```
