### ISSUE TITLE
Bump needed ruby version for forge release

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#135]
Our current release part in the [.travis.yml](https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.travis.yml#L65):
```yaml
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
    condition: "$FUTURE_PARSER = yes"
```

We should bump that, we don't test on 1.9.3 anymore. Which version do we want to target here? 2.3.0? I would use that one because it does rubocp + spec tests. But then we may remove 2.3.0 from the allow_failures category.
