### ISSUE TITLE
fix broken defaults for spec_helper.rb

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#174]
We currently have the following hash:
```yaml
spec/spec_helper.rb:
  default_facts:
    concat_basedir: '/tmp'
    is_pe: false
    selinux_config_mode: 'disabled'
    puppetversion: Puppet.version
    facterversion: Facter.version
    ipaddress: '172.16.254.254'
    macaddress: 'AA:AA:AA:AA:AA:AA'
```

which results in [this](https://github.com/voxpupuli/puppet-minecraft/blob/9669e52895aab19664e53bd09bd69db69131a278/spec/spec_helper.rb):
```ruby
RSpec.configure do |c|
  c.default_facts = {
    concat_basedir: /tmp
    is_pe: false
    selinux_config_mode: disabled
    puppetversion: Puppet.version
    facterversion: Facter.version
    ipaddress: 172.16.254.254
    macaddress: AA:AA:AA:AA:AA:AA
  }
end
```

But it has to be [this](https://github.com/voxpupuli/puppet-minecraft/commit/053f422ba8eb25a48da16a19bc161a9c8e0e7307):
```ruby
RSpec.configure do |c|
  c.default_facts = {
    concat_basedir: '/tmp',
    is_pe: false,
    selinux_config_mode: 'disabled',
    puppetversion: Puppet.version,
    facterversion: Facter.version,
    ipaddress: '172.16.254.255',
    macaddress: 'AA:AA:AA:AA:AA:AA',
  }
```

Can we please test modulesync_config changes on a single module before we merge it?
