### ISSUE TITLE
add new cops for more space?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#189]
We've a few cops that enforce space:

```
Style/SpaceBeforeComment:
  Enabled: true
Style/SpaceBeforeSemicolon:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true

Style/SpaceInsideBrackets:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true

Style/LeadingCommentSpace:
  Enabled: true

Style/SpaceBeforeFirstArg:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/SpaceAfterSemicolon:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: true

Style/SpaceBeforeComma:
  Enabled: true

Style/SpaceBeforeFirstArg:
  Enabled: true
```

rubocop 0.41 introduced a few new cops:

```
Style/SpaceInsideArrayPercentLiteral
Style/SpaceInsidePercentLiteralDelimiters
```

Do we want to enable them as well?
