### ISSUE TITLE
Add new .travis.yml section for beaker-docker tests

### ISSUE THREAD

**Issue by petems** [voxpupuli/modulesync_config#80]
Although we have PCCI for acceptance testing, since it's fairly easy to setup Beaker to docker tests in Travis CI, might be an idea to add that as a configurable section to the .travis.yml for modules?

``` yaml
matrix:
  include:
    - rvm: '2.1'
      sudo: required
      services: docker
      env: PUPPET_VERSION="3.8.4" BEAKER_set="centos-6-docker"
      script: bundle exec rspec spec/acceptance/class_spec.rb
      bundler_args: --without development
  allow_failures:
    - env: PUPPET_VERSION="3.8.4" BEAKER_set="centos-6-docker"
```

Add new Beaker SUT: 

``` yaml
HOSTS:
  centos-6-x64:
    platform: el-6-x86_64
    hypervisor : docker
    image: centos:6
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'yum install -y crontabs tar wget'
CONFIG:
  type: foss
  log_level: debug
```
