### ISSUE TITLE
Remove tight coupling to gha-puppet in gha workflow templates

### ISSUE THREAD

**Issue by h-haaks** [voxpupuli/modulesync_config#887]
When adding new inputs to files in https://github.com/voxpupuli/gha-puppet/tree/v2/.github/workflows we always have to make changes to https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.github/workflows/ci.yml.erb to reflect this.

By adding a 'with' key to .sync.yml and checking `@configs['with']` in ci.yml.erb we could remove this tight copling.

Sample `.sync.yml`
```
.github/workflows/ci.yml:
  with:
    beaker_hosts: 'host1:shard.ma;host2:slave,router.a'
    beaker_facter: 'mongodb_repo_version:MongoDB:4.4,5.0,6.0,7.0'
```
